ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
  skip: [poetry-lock, poetry-export]
repos:
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.260'
    hooks:
    - id: ruff
      args: [--fix]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "sds_data_manager/lambda_code/requirements.txt", "--only", "lambda-dev"]
        verbose: true