ci:
  autofix_prs: false
  autoupdate_schedule: 'quarterly'
  skip: [poetry-lock, poetry-export]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: detect-aws-credentials
        args: [ --allow-missing-credentials ]
      - id: detect-private-key
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [--branch, main, --branch, dev]
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.0.292'
    hooks:
    - id: ruff
      args: [--fix]
  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.0'  # add version here
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args: [--no-update]
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "sds_data_manager/lambda_code/requirements.txt", "--only", "lambda-dev"]
        verbose: true
