version: "3.9"
services:
  imap_sdc:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile # path to Dockerfile
    image: sds_data_manager
    stdin_open: true # This line is same as docker run -i
    tty: true # This line is same as docker run -t
    volumes: # mount volumes
      - .:/workspaces/sds-data-manager/
      - $HOME/.aws:/workspaces/sds-data-manager/.aws/
    # env_file: # Set environment variables using .env file
    #   - ./sds_data_manager/SDSCode/lambda.env