[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "sds-data-manager"
version = "0.1.0"
description = "IMAP Science Operations Center AWS data manager"
authors = ["Greg Lucas <greg.lucas@lasp.colorado.edu>, Bryan Harter <bryan.harter@lasp.colorado.edu>, Sean Hoyt <sean.hoyt@lasp.colorado.edu>, Tenzin Choedon <tenzin.choedon@lasp.colorado.edu>"]
readme = "README.md"
license = "MIT"
keywords = ["IMAP", "SDC", "SOC", "Science Operations"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]

[tool.poetry.dependencies]
python = ">=3.9,<4"
# Required for aws-cdk.aws-lambda-python-alpha
aws-cdk-lib = ">=2.66.0,<3.0.0"
#aws-cdk-lib = "2.48.0"
boto3 = "^1.26.78"
"aws-cdk.aws-lambda-python-alpha" = "^2.66.0a0"
constructs = ">=10.0.0,<11.0.0"

# Installed by default, can be installed without these dependencies using `poetry install --without tests`
black = "^23.1.0"
[tool.poetry.group.tests.dependencies]
pytest = "==6.2.5"
moto = "^4.1.3"

# Not installed by default, can be installed using `poetry install --with cdk`
[tool.poetry.group.cdk]
optional = true

[tool.poetry.group.cdk.dependencies]
opensearch-py = "^2.1.1"
requests = "^2.28.2"
python-jose = "^3.3.0"

[project.urls]
homepage = "https://github.com/IMAP-Science-Operations-Center"
repository = "https://github.com/IMAP-Science-Operations-Center/sds-data-manager"

