[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "sds_data_manager"
version = "0.1.0"
description = "IMAP Science Operations Center SDS-data-manager"
readme = "README.md"
license = {text = "MIT"}
keywords = ["IMAP", "SDC", "SOC", "Science Operations"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]
requires-python = ">=3.9"
dependencies = [
    "aws-cdk.aws-lambda-python-alpha",
    "aws-cdk-lib>=2.48.0,<3.0.0",
    "constructs>=10.0.0,<11.0.0",
]

[project.optional-dependencies]
test = [
    "moto",
    "pytest",
]

dev = [
    "black",
    "pre-commit",
    "ruff",
    "sds_data_manager[test]"
]

[project.urls]
homepage = "https://github.com/IMAP-Science-Operations-Center"
repository = "https://github.com/IMAP-Science-Operations-Center/sds-data-manager"

[tool.pytest.ini_options]
testpaths = [
  "tests",
]
addopts = "-ra"
markers = [
    "network: Test that requires network access",
]

[tool.ruff]
target-version = "py39"
select = ["B", "E", "F", "I", "N", "S", "W", "PL", "PT", "UP", "RUF"]
# Ignore import sorting for now until lines_after_imports is respected
# by ruff and we can replace isort
ignore = ["D203", "D212", "PLR0913", "PLR2004"]

[tool.ruff.per-file-ignores]
"tests/*" = ["S"]
