"""create_release_file_table.

Revision ID: 2e02fb28e9a5
Revises: e9295ca9d77e
Create Date: 2026-05-08 07:37:49.248429

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2e02fb28e9a5"
down_revision: str | Sequence[str] | None = "e9295ca9d77e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release_files",
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column(
            "instrument",
            sa.Enum(
                "hi",
                "mag",
                "ultra",
                "swe",
                "idex",
                "swapi",
                "hit",
                "ialirt",
                "glows",
                "lo",
                "codice",
                "spacecraft",
                name="instrument",
            ),
            nullable=False,
        ),
        sa.Column("descriptor", sa.String(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("version", sa.String(length=4), nullable=False),
        sa.Column("extension", sa.String(), nullable=False),
        sa.Column("ingestion_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("released", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("file_path"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("release_files")
    # ### end Alembic commands ###
