"""update_version_in_idex_l0_table.

Revision ID: 320be9613edc
Revises: f52014ca1da4
Create Date: 2026-05-08 15:37:17.152048

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "320be9613edc"
down_revision: str | Sequence[str] | None = "f52014ca1da4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "idex_l0_files",
        "version",
        existing_type=sa.VARCHAR(length=2),
        type_=sa.String(length=4),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "idex_l0_files",
        "version",
        existing_type=sa.String(length=4),
        type_=sa.VARCHAR(length=2),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
