"""Stores the downstream dependency configuration of Ultra.

This is used to populate pre-processing dependency table in the database.

NOTE: This setup assumes that we get one data file with multiple APIDs data.
This is why we have only one dependency for l0. We expect that we get one
l0 file, eg. imap_ultra_l0_raw_20240529_v001.pkts, which contains all the data of all
APIDs. That l0 data file will kick off one l1a process for 'all' as l1a will produce
multiple files with different descriptor(aka different data product per APID). Those
different descriptor are handled by CDF attrs.
"""

from ..database.models import PreProcessingDependency

# TODO: fix ultra dependency because it's not kicking processing when new data
# is available
downstream_dependents = [
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l0",
        primary_descriptor="raw",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # Ultra-45
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="45de",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="45phxtof",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="45aux",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="45rates",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # TODO: uncomment for post-SIT-3
    # PreProcessingDependency(
    #     primary_instrument="codice",
    #     primary_data_level="l2",
    #     primary_descriptor="todo",
    #     dependent_instrument="ultra",
    #     dependent_data_level="l1b",
    #     dependent_descriptor="45all",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    # PreProcessingDependency(
    #     primary_instrument="swapi",
    #     primary_data_level="l2",
    #     primary_descriptor="todo",
    #     dependent_instrument="ultra",
    #     dependent_data_level="l1b",
    #     dependent_descriptor="45all",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45annotated-de",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45extended-spin",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45culling-mask",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45badtimes",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="45all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # Ultra-90
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="90de",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="90phxtof",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="90aux",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="90rates",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # TODO: uncomment for post-SIT-3
    # PreProcessingDependency(
    #     primary_instrument="codice",
    #     primary_data_level="l2",
    #     primary_descriptor="todo",
    #     dependent_instrument="ultra",
    #     dependent_data_level="l1b",
    #     dependent_descriptor="90all",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    # PreProcessingDependency(
    #     primary_instrument="swapi",
    #     primary_data_level="l2",
    #     primary_descriptor="todo",
    #     dependent_instrument="ultra",
    #     dependent_data_level="l1b",
    #     dependent_descriptor="90all",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90annotated-de",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90extended-spin",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90culling-mask",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90badtimes",
        dependent_instrument="ultra",
        dependent_data_level="l1c",
        dependent_descriptor="90all",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
]

# UPSTREAM DEPENDENCIES
upstream_dependents = [
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1a",
        primary_descriptor="all",
        dependent_instrument="ultra",
        dependent_data_level="l0",
        dependent_descriptor="raw",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # Ultra-45
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="45de",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="45phxtof",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="45aux",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="45rates",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # TODO: uncomment for post-SIT-3
    # PreProcessingDependency(
    #     primary_instrument="ultra",
    #     primary_data_level="l1b",
    #     primary_descriptor="45all",
    #     dependent_instrument="codice",
    #     dependent_data_level="l2",
    #     dependent_descriptor="todo",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    # PreProcessingDependency(
    #     primary_instrument="ultra",
    #     primary_data_level="l1b",
    #     primary_descriptor="45all",
    #     dependent_instrument="swapi",
    #     dependent_data_level="l2",
    #     dependent_descriptor="todo",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45annotated-de",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45extended-spin",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45culling-mask",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="45all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="45badtimes",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # Ultra-90
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="90de",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="90phxtof",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="90aux",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1b",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1a",
        dependent_descriptor="90rates",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    # TODO: uncomment for post-SIT-3
    # PreProcessingDependency(
    #     primary_instrument="ultra",
    #     primary_data_level="l1b",
    #     primary_descriptor="90all",
    #     dependent_instrument="codice",
    #     dependent_data_level="l2",
    #     dependent_descriptor="todo",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    # PreProcessingDependency(
    #     primary_instrument="ultra",
    #     primary_data_level="l1b",
    #     primary_descriptor="90all",
    #     dependent_instrument="swapi",
    #     dependent_data_level="l2",
    #     dependent_descriptor="todo",
    #     relationship="HARD",
    #     direction="DOWNSTREAM",
    # ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90annotated-de",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90extended-spin",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90culling-mask",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
    PreProcessingDependency(
        primary_instrument="ultra",
        primary_data_level="l1c",
        primary_descriptor="90all",
        dependent_instrument="ultra",
        dependent_data_level="l1b",
        dependent_descriptor="90badtimes",
        relationship="HARD",
        direction="DOWNSTREAM",
    ),
]
