FROM public.ecr.aws/lambda/python:3.12

COPY processing/requirements.txt ./requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY SDSCode/pipeline_lambdas/idex_l0_indexer.py .

CMD ["idex_l0_indexer.lambda_handler"]