name: Tests

on:
  push:
    branches:
      - main
      - development
  pull_request:

jobs:
  cdk-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install the app
        run: |
          python -m pip install -e .[dev]

      - name: Testing
        id: test
        run: |
          # Ignore the network marks from the remote test environment
          python -m pytest --color=yes -m "not network"
