name: Tests

on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  cdk-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - uses: Gr1N/setup-poetry@v8

      - name: Install dependencies and app
        run: |
          poetry install --with lambda-dev

      - name: Testing
        id: test
        env:
          AWS_DEFAULT_REGION: us-west-1
        run: |
          # Ignore the network marks from the remote test environment
          poetry run pytest --color=yes --cov --cov-report=xml -m "not network"

      - name: Upload code coverage
        uses: codecov/codecov-action@v3
