name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cdk-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v8

      - name: Install dependencies and app
        run: |
          poetry install --with cdk
      
      - name: Testing
        id: test
        run: |
          # Ignore the network marks from the remote test environment
          poetry run pytest --color=yes -m "not network"